FROM --platform=linux/amd64 continuumio/miniconda3

RUN conda install -y pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
RUN conda install -y jupyterlab ipywidgets

RUN mkdir /opt/notebooks
WORKDIR /opt/notebooks

EXPOSE 8888
CMD jupyter lab --allow-root --ip='*' --no-browser --port=8888 --notebook-dir=/opt/notebooks